version: '3'
services:
  service-a:
    build:
      context: .
      dockerfile: service-a/Dockerfile
    ports:
      - "8081:8081"
  service-b:
    build:
      context: .
      dockerfile: service-b/Dockerfile
    ports:
      - "8082:8082"
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"     # Jaeger UI  
      - "6831:6831/udp"   # Thrift Udp Compact  
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT
    command: ["--reporter.grpc.host-port=otel-collector:14250"] 

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.52.0
    container_name: otel-datadog
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./config.yaml:/etc/otel-collector-config.yml
    ports:
      - "8888:8888"
      - "13133:13133" # health_check extension
      - "14268:14268"
      - "14269:14269"
    depends_on:
      - jaeger
 
  
